preload = /home/villegas/Images/dark.jpg
# Cambia HDMI-A-2 por el nombre real de tu monitor si falla
wallpaper = , /home/villegas/Images/dark1.jpg
# Desactiva el texto de abajo (splash)
splash = false
