preload = /home/villegas/Images/dark.jpg
# Cambia HDMI-A-2 por el nombre real de tu monitor si falla
wallpaper = HDMI-A-2, /home/villegas/Images/dark8.jpg
# Desactiva el texto de abajo (splash)
splash = false
