return {
  { icon = "✓ ", name = "approved" },
  { icon = "✗ ", name = "completed" },
  { icon = "⦿ ", name = "goal" },
  { icon = "● ", name = "circle" },
  { icon = "▰ ", name = "black paralelogram" },
  { icon = "🗲 ", name = "idea" },
  { icon = "━ ", name = "note" },
  { icon = "∕ ", name = "onw | on work" },
  { icon = "⦁ ", name = "task" },
  { icon = "🞧 ", name = "expand concept/idea" },
  { icon = "‼ ", name = "urgent" },
  { icon = "✪ ", name = 'star' },
  { icon = "⛬ ", name = 'tasks' },
  { icon = "▷ ", name = 'migrated | moved' },
  { icon = "🞾 ", name = 'important' },
  { icon = "⋗ ", name = 'migrated | moved' },
  { icon = "?‼ ", name = 'important question' },
  { icon = "?? ", name = "question" },
  { icon = "󰨰 ", name = "bug" },
}
