return {}
--
-- return {
--   -- Usamos un plugin dummy para inyectar comandos y mapeos
--   {
--     "LazyVim/LazyVim",
--     -- Definimos la configuración en `opts` para inyectar comandos de usuario
--     opts = {
--       -- Comando de usuario para crear una nueva tarea
--       {
--         "AddTask",
--         function()
--           local todo_file = vim.fn.getcwd() .. "/todo.md"
--           local msg = vim.fn.input("Nueva Tarea: ")
--
--           if msg ~= "" then
--             -- Asegura que el archivo exista antes de escribir
--             if vim.fn.filereadable(todo_file) == 0 then
--               vim.fn.writefile({ "# Tareas del Proyecto" }, todo_file)
--             end
--
--             -- Añade la nueva tarea al final del archivo
--             local file = io.open(todo_file, "a")
--             if file then
--               file:write("- [ ] " .. msg .. "\n")
--               file:close()
--               vim.notify("Tarea '" .. msg .. "' añadida a " .. todo_file, vim.log.levels.INFO)
--             else
--               vim.notify("Error al abrir el archivo " .. todo_file, vim.log.levels.ERROR)
--             end
--           end
--         end,
--         desc = "Añadir nueva tarea a todo.md",
--       },
--     },
--     -- Definimos los mapeos de teclas en `keys`
--     keys = {
--       -- Mapeo para alternar la ventana lateral de tareas
--       {
--         "<leader>tt",
--         function()
--           local todo_file = vim.fn.getcwd() .. "/todo.md"
--           local width = 50 -- Ancho de la ventana lateral (ajustable)
--
--           -- 1. Buscar si el buffer de todo.md ya está abierto en una ventana
--           local todo_win = nil
--           for _, winid in ipairs(vim.api.nvim_list_wins()) do
--             if vim.api.nvim_win_get_buf(winid) == vim.fn.bufnr(todo_file) then
--               todo_win = winid
--               break
--             end
--           end
--
--           if todo_win then
--             -- 2. Si está abierto, cerrarlo
--             vim.api.nvim_win_close(todo_win, true)
--           else
--             -- 3. Si no está abierto, crearlo
--             -- Asegura que el archivo exista antes de abrir
--             if vim.fn.filereadable(todo_file) == 0 then
--               vim.fn.writefile({ "# Tareas del Proyecto" }, todo_file)
--             end
--
--             -- Abrir en un vsplit a la derecha
--             vim.cmd("vsplit")
--             vim.cmd("wincmd L") -- Mover a la derecha extrema
--             vim.cmd("vertical resize " .. width)
--             vim.cmd("edit " .. todo_file)
--             -- Solo mantenemos la opción para fijar el ancho
--             vim.cmd("setlocal winfixwidth") -- Fija el ancho
--           end
--         end,
--         desc = "Toggle Tareas del Proyecto (todo.md) Sidebar",
--       },
--       -- Mapeo para crear tarea
--       { "<leader>tc", ":AddTask<CR>", desc = "Crear Tarea" },
--     },
--   },
-- }
