# vim:ft=kitty

## name:     Catppuccin-Mocha (Matrix Mod)
## author:   Pocco81 (Modified for Matrix look)
## license:  MIT
## blurb:    Soothing cyber-green theme for the high-spirited!

# The basic colors
foreground              #A6E3A1
background              #000000
selection_foreground    #000000
selection_background    #00FF33

# Cursor colors
cursor                  #00FF33
cursor_text_color       #000000

# URL underline color when hovering with mouse
url_color               #00FF33

# Kitty window border colors
active_border_color     #00FF33
inactive_border_color   #313244
bell_border_color       #F9E2AF

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #000000
active_tab_background   #00FF33
inactive_tab_foreground #A6E3A1
inactive_tab_background #11111B
tab_bar_background      #000000

# Colors for marks (marked text in the terminal)
mark1_foreground #000000
mark1_background #00FF33
mark2_foreground #000000
mark2_background #A6E3A1
mark3_foreground #000000
mark3_background #74C7EC

# The 16 terminal colors

# black
color0 #1E1E2E
color8 #45475A

# red (mantenemos un toque sutil oscuro)
color1 #F38BA8
color9 #F38BA8

# green (el color principal de Matrix)
color2  #A6E3A1
color10 #00FF33

# yellow
color3  #F9E2AF
color11 #F9E2AF

# blue (lo cambiamos a verde azulado/cibernético oscuro)
color4  #006633
color12 #009944

# magenta (cambiado a verde oliva/oscuro)
color5  #336633
color13 #448844

# cyan
color6  #94E2D5
color14 #94E2D5

# white
color7  #BAC2DE
color15 #A6ADC8
