## name:     Matrix Smooth Contrast
## blurb:    Esquema de color suavizado basado en The-Matrix.nvim

# Colores fundamentales (Coinciden con Neovim)
background              #0D1117
foreground              #22DA6E
selection_background    #0E4D24
selection_foreground    #55FF99
url_color               #00FF66
cursor                  #00FF66
cursor_text_color       #0D1117

# Bordes de ventanas de Kitty
active_border_color     #1A8A47
inactive_border_color   #0A2912

# Barra de pestañas (Tabs)
active_tab_background   #00FF66
active_tab_foreground   #0D1117
inactive_tab_background #090D12
inactive_tab_foreground #1A6E39
tab_bar_background      #05080C

# Los 16 colores de la terminal calibrados
# Black (Tonos oscuros de fondo)
color0 #0D1117
color8 #1A6E39

# Red (Alertas suaves)
color1 #D64545
color9 #A63232

# Green (Verdes principales de lectura)
color2  #22DA6E
color10 #00FF66

# Yellow
color3  #C2D625
color11 #E6A122

# Blue
color4  #1DB954
color12 #1AA34A

# Magenta
color5  #22DA88
color13 #1AD161

# Cyan
color6  #33CC77
color14 #55FF99

# White
color7  #6BECA4
color15 #99FFBB
